AWSTemplateFormatVersion: '2010-09-09'
Description: RDS MySQL

Parameters:
  VpcId:
    Type: String
  PrivateSubnet:
    Type: String
  EC2SecurityGroup:
    Type: String

Resources:

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: MySQL desde EC2
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref EC2SecurityGroup

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet privada
      SubnetIds:
        - !Ref PrivateSubnet

  MyRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t3.micro
      Engine: mysql
      AllocatedStorage: 20
      MasterUsername: admin
      MasterUserPassword: Admin1234!
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup

Outputs:
  RDSEndpoint:
    Value: !GetAtt MyRDS.Endpoint.Address