AWSTemplateFormatVersion: '2010-09-09'
Description: Bucket S3 para backups

Resources:
  BackupBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

Outputs:
  BucketName:
    Value: !Ref BackupBucket